Review 3
LeraFrans/Yadro_course pull request #8
Opened 2024-04-16 06:31 UTC by LeraFrans

Здравствуйте! Это было правда сложно... :)

Сделала параллелизацию и кэширование. Недоделаны пока остались флаг -с для поиска конфигурационного файла и определение максимального количества комиксов.

(Если объяснение тут и код останутся непонятными, записала небольшое видео с разговорным объяснением и демонстрацией работы программы, демонстрация запуска в конце видео) 
https://youtu.be/1sXQsek0_cM

Несколько основных реализованных идей:
- Есть канал numbers в который помещаются номера комиксов, подлежащих обработке. Обычно там все номера от 0 до 2916. Но если программа была приостановлена, то в этот канал не помещаются номера комиксов, которые уже были обработаны и записаны в предыдущий раз.
- В цикле параллельно запускается 7 горутин, в них происходит считывание и обработка одного комикса. Внутри этой горутины есть ещё одно горутина, которая производит запись комикса в результирующую мапу, защищая запись мьютексами.
- Кэша как такового нет. Просто как только комикс записался в результирующую мапу, его номер записывается в слайс и при остановке программы, этот слайс переписывается в файл-кэш "written_comics.txt". А при повторном запуске информация из файла-кэша используется при записи номеров в канал numbers.
- В кэш не записываются комиксы, которые считались с сайта, но не успели записаться в результирующую мапу. Но при моей реализации отставание между чтением и записью буквально в 2-3 комикса, так что это незначительная потеря времени.
- Обработка сигнала SIGINT через создание канала, ожидающего на вход системный сигнал. 

Пыталась сделать другую логику конкурентности, например:
- Создание двух горутин: одна на чтение с сайта, вторая на запись в результирующую мапу. И между ними канал, по которому идут обработанные данные от горутины чтения в горутину записи.
- Примерно то же самое, но с использованием Select
Но оба варианта не получились особо, поэтому вернулась в к тому, что есть, хоть он и получился не очень быстрым в итоге (30-80 секунд на мобильном интернете при 7 параллельно работающих горутинах) 

К дедлайну доделаю подсчёт максимального числа комиксов на сайте и флаг -с. 
Спасибо за проверку!

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +func parsArguments() (bool, int) {
тут небольшая ошибка в названии parseArguments

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +func readConfig() (string, string) {
Конфигурационные файлы проще всего сразу парсить в структуру config, а не в map[string].
Чтение конфигурационного файла и параметров командной строки обычно делают в main файле, и если что-то идет не так, то можно остановить программу

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +func MakeJSONwithComicsData() {
W лучше с большой буквы MakeJSONWithComicsData

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +func MakeJSONwithComicsData() {
У тебя получилась не расширяемая функция - т.е. она будет работать только с конфигом с аргументами переданными в командную строку. Лучше такие параметры передавать через аргументы функции

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +	if err != nil {
Тут не хватает обработки ошибок! В данном случае ты обрабатываешь только ошибку самого клиента и сразу начинаешь парить тело запроса. А ведь в ответ может прийти не только resp.StatusCode == 200, а например еще и 500 или 404 и другие ошибки

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +type InputData struct {
Я бы переименовал эту структуру в ResponseData

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +func checkFileIsExist(filename string) error {
Тут можно фкнкцию назвать либо checkFileIsExists или isFileIsExists

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +		_, err := os.Create(filename)
Я в фкункции checkFileIsExists не ожидаю создания файла. Все же тогда функцию надо назвать - createFileIfNotExist

2024-04-16 15:48 UTC, kirreal commented on Task2/comic/createJSON.go
> +	nFlag := flag.Bool("n", false, "Флаг -n")
Флаги проще парить через flag.BoolVar(&var)

2024-04-16 15:49 UTC, kirreal commented
Пока посмотрел только второе задание - лучше делать отдельный PR на каждое задание, а то очень неудобно смотреть

2024-04-16 16:40 UTC, kirreal requested changes

2024-04-16 16:40 UTC, kirreal commented on Task3/comic/createJSON.go
> +func getDataOfOneComic(num int, source_url string) InputData {
Эту функцию можно было бы назвать getCommic

2024-04-16 16:40 UTC, kirreal commented on Task3/comic/createJSON.go
> +		log.Fatal(err)
Fatal вызовет панику, в целом, если будет ошибка в обработке одного из комиксов это не должно выполнять остановку программы, возможно, остальные будут правильные

2024-04-16 16:40 UTC, kirreal commented on Task3/comic/createJSON.go
> +func readCashe(filename string) (bool, []byte) {
readCache

2024-04-16 16:40 UTC, kirreal commented on Task2/comic/createJSON.go
> +	content, err := os.ReadFile("config.yaml")
В задании было указано:  -с флаг для нахождения конфига, единственный флаг приложения, т.е. конфигурация надо получать через флаг, а этот вариант оставить на случай, если флаг не указан

2024-04-16 16:40 UTC, kirreal commented on Task2/comic/createJSON.go
> +	for num := 1; num <= max_num; num++ {
Тут должна быть реализована логика получения только тех комиксов, которые мы не получили ранее

2024-04-16 19:21 UTC, LeraFrans commented on Task3/comic/createJSON.go
> +func writeResultInJSON(resultMap map[int]OutputData, db_file string) {
Спасибо за ревью!
Не совсем поняла, что за функции getByID и getAll, у меня нет таких. Тут просто из мапы записываю данные в json. Получать из json обратно что-то нам не надо потом по таску, вроде как

2024-04-16 19:23 UTC, LeraFrans commented on Task2/comic/createJSON.go
> +	content, err := os.ReadFile("config.yaml")
Это папка таск 2, во втором задании были другие флаги. Вариант с единственным флагом -с лежит в папке Task3 (вообще проект по версии задания этой недели лежит полностью в папке Task3, папка  Task2 это предыдущая неделя)

2024-04-16 19:24 UTC, LeraFrans commented on Task2/comic/createJSON.go
> +	for num := 1; num <= max_num; num++ {
Аналогично. Это Task2, нужно смотреть в папку Task3

2024-04-17 15:25 UTC, kirreal approved these changes

2024-04-18 07:36 UTC, closed without merging